### ISSUE TITLE
Escoger proyecto para la materia

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#1]
Cómo Equipo RAC 
Queremos escoger un proyecto que cumpla los requisitos de la materia
Para poder planificar y desarrollar el mismo

**Comment by CesarIll** [comment]
El proyecto se escogió de acuerdo a coordinación con docente por el uso de un proyecto para una feria de la Universdad Privada Boliviana

**Comment by RobertoCuevasP** [comment]
El proyecto ya fue seleccionado y adaptado a los requisitos de la materia. Tarea cerrada.
