### ISSUE TITLE
Arquitectura Back-end

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#10]
Como desarrollador
Quiero mostrar el funcionamiento y los flujos de datos mediante las tecnologías empleadas
Para ver cómo deben conectare para software que se vaya a utilizar

**Comment by CesarIll** [comment]
17/11/2020 -> Mediante una reunión Zoom y haciendo uso de Diagrams.net, se hicieron los diagramas para la arquitectura de back-end
18/11/2020 -> Se hizo la corrección del diagrama de arquitectura de back-end
