### ISSUE TITLE
Nombre y logo de videojuego

### ISSUE THREAD

**Issue by CesarIll** [RAC-Assures-Creativity/RAC-Assures-Creativity#16]
Como creadores del videojuego 
Queremos pensar en ideas para el nombre y logo del videojuego
Tal que sean llamativos, innovadores y comerciales

**Comment by RobertoCuevasP** [comment]
A día 19/11/2020 aún falta decidir un nombre atractivo así como el logo

**Comment by RaisaSilva** [comment]
23/11/2020 -> Logo inicial terminado
21/11/2020 -> Se decidió el nombre del videojuego: "Peace Fopi!"
