### ISSUE TITLE
Diagrama de Base de Datos

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#19]
Como desarrolladores 
Queremos crear un diagrama de base de datos
Para mostrar el funcionamiento de la misma dentro de nuestro programa

**Comment by CesarIll** [comment]
Preguntar acerca del diagrama de base de datos a presentar. Cómo sería para una base de datos no relacional como el que usa Realtime Database de Firebase?

**Comment by RobertoCuevasP** [comment]
El día jueves 3 de Diciembre se realizó el Diagrama de Base de Datos no Relacional mostrando cómo sería la misma empleando JSON
