### ISSUE TITLE
Introducción del proyecto

### ISSUE THREAD

**Issue by RaisaSilva** [RAC-Assures-Creativity/RAC-Assures-Creativity#2]
Como editor
Quiero hacer la introducción del proyecto
Tal que se entienda el motivo por el cual se hace el videojuego

**Comment by CesarIll** [comment]
13/11/2020 -> Se hicieron cambios en la Wiki por Raisa, Roberto y Cesar.
16/11/2020 -> Se hicieron cambios en la Wiki por Raisa
