### ISSUE TITLE
Página de Login

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#20]
Como desarrollador
Quiero una interfaz de login funcional
Para que el usuario pueda registrar y emplear su cuenta

**Comment by RobertoCuevasP** [comment]
Ya se terminó la página de Login, tiene una característica diferente a los demás menús, @RaisaSilva puedes revisarlo como ayuda a que el menú encaje en la cámara.

**Comment by RaisaSilva** [comment]
si estoy de acuerdo.

**Comment by RobertoCuevasP** [comment]
Con la base de datos ya creada, se realizó la conexión correspondiente, se pueden crear usuarios así cómo solicitar uno ya creado.
