### ISSUE TITLE
Implementación caso de uso: Diseño Nivel 1

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#21]
Cómo diseñador
Quiero tener los diseños del primer nivel terminados
Para poder emplearlos en el desarrollo del Nivel 1

**Comment by RaisaSilva** [comment]
23/11/20 El escenario del primer nivel sigue en proceso

**Comment by RaisaSilva** [comment]
Diseños del nivel 1 ya están terminados e implementados en el videojuego.
