### ISSUE TITLE
Implementación Casos de Uso: Scripts Personajes

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#22]
Cómo desarrollador 
Quiero realizar los códigos de los personajes (movimientos, ataque, vida)
Para crear objetos con los scripts junto a los diseños

**Comment by RaisaSilva** [comment]
Una vez terminados los diseños de cada personaje (frontal, espaldar, de lado derecho y de lado izquierdo) se podrá realizar los respectivos scripts.

**Comment by RobertoCuevasP** [comment]
El día 26/11/20 se crearon los scripts necesarios para el personaje, como son la vida, su movimiento y ataques.
