### ISSUE TITLE
Implementación Casos de Uso: Menú Principal

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#23]
Cómo desarrolladores y diseñadores
Queremos implementar un menú principal
Para tener una UI

**Comment by RaisaSilva** [comment]
El día de hoy martes 1 de diciembre, los menús salen en diferentes tamaños, debemos encontrar una forma en la que sea estándar para todos.

**Comment by RobertoCuevasP** [comment]
Para la estandarización de los menús, se tomó en cuenta el tamaño de cámara 16:9. Aún persisten ciertos detalles, sin embargo, no representan un mayor problema.
