### ISSUE TITLE
Creación y configuración de repositorios

### ISSUE THREAD

**Issue by CesarIll** [RAC-Assures-Creativity/RAC-Assures-Creativity#24]
Como miembros
Queremos configurar los repositorios
Tal que podamos empezar a desarrollar

**Comment by CesarIll** [comment]
Nos quedamos con el repositorio de Prueba (y le cambiamos el nombre si se puede) o nos creamos otro?

**Comment by RobertoCuevasP** [comment]
Finalmente nos quedamos con el repositorio de prueba bajo el nuevo nombre de "Unity".
