### ISSUE TITLE
Implentación Casos de Uso: Menú crear/unirse partida

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#29]
Como desarrolladores
Queremos implementar un menú que permita crear o unirse a una partida
Para diferenciar a los 2 tipos de usuario y tener un puente al registro de usuarios

**Comment by RaisaSilva** [comment]
El día de ayer Lunes 30 de noviembre, Roberto y yo completamos este issue.
