### ISSUE TITLE
Implementación de menú - Configuración general

### ISSUE THREAD

**Issue by RaisaSilva** [RAC-Assures-Creativity/RAC-Assures-Creativity#35]
Como desarrollador
Quiero crear un menú de configuración general (audio y gráficos)
Para la conexión con el scenario de menú principal

**Comment by RobertoCuevasP** [comment]
El día de hoy martes 1 de diciembre, los menús salen en diferentes tamaños, debemos encontrar una forma en la que sea estándar para todos.
