### ISSUE TITLE
Conexión Página Login con la base de datos

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#37]
Cómo desarrolladores
Queremos conectar el login con la base de datos
Para tener un sistema backend completo

**Comment by RaisaSilva** [comment]
Cuando este conectado con la base de datos, se deben modificar algunos botones del videojuego.

**Comment by CesarIll** [comment]
03/12/2020 -> Se logró la conexión de la página de login con el servicio backend para la validación de usuario y se modificó los botones correspondientes.
