### ISSUE TITLE
Arreglar Conflicto Github

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#38]
Cómo desarrolladores
Queremos arreglar los conflictos en Github
Para seguir trabajando con el proyecto

**Comment by RaisaSilva** [comment]
El día 16/12/20 se soluciono el conflicto en github

**Comment by CesarIll** [comment]
Cabe recalcar que se llevó el HEAD a un commit anterior y se forzó a los repositorios remotos a volver a este estado para eliminar el conflicto.
