### ISSUE TITLE
Diagrama Arquitectura General

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#8]
Cómo desarrolladores
Queremos mostrar cómo se comporta el videojuego y sus interacciones entre usuario y sistema a un alto nivel
Para entender e implementarlo más adelante de forma correcta

**Comment by CesarIll** [comment]
17/11/2020 -> Mediante una reunión Zoom y haciendo uso de Diagrams.net, se hicieron los diagramas para la arquitectura general
18/11/2020 -> Se hizo la corrección del diagrama de arquitectura general
