### ISSUE TITLE
Arquitectura Front-end

### ISSUE THREAD

**Issue by RobertoCuevasP** [RAC-Assures-Creativity/RAC-Assures-Creativity#9]
Cómo desarrolladores
Queremos realizar un diagrama que muestre como será la interacción visual entre el usuario y el videojuego
Para entender cómo un cliente verá y usará nuestro producto

**Comment by CesarIll** [comment]
17/11/2020 -> Mediante una reunión Zoom y haciendo uso de Diagrams.net, se hicieron los diagramas para la arquitectura de front-end
18/11/2020 -> Se hizo la corrección del diagrama de arquitectura de front-end
